CREATE DATABASE UNOaUNO
GO
USE UNOaUNO
GO

CREATE TABLE Ubicacion(
	Legajo BIGINT NOT NULL PRIMARY KEY,
	Localidad VARCHAR(150) NOT NULL,
	Telefono VARCHAR(150) NOT NULL
)
GO

ALTER TABLE Ubicacion
ADD CONSTRAINT FK_Ubicacion FOREIGN KEY (Legajo) REFERENCES Empleados (Legajo)
GO

CREATE TABLE Empleados(
	Legajo BIGINT NOT NULL PRIMARY KEY,
	Apellido VARCHAR(150) NOT NULL,
	Nombre VARCHAR(150) NOT NULL,
	DNI VARCHAR(20) NOT NULL UNIQUE,
)
GO